apiVersion: v1
kind: Service
metadata:
  name: my-angular-app-service
  namespace: my-angular-app
spec:
  selector:
    app: my-angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
