version: "3.2"
services:
  php:
    build: './docker/php/'
    networks:
      - backend
    volumes:
      - ./src/:/var/www/html/
  apache:
    build: './docker/apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "4201:80"  
    networks:
      - frontend
      - backend
    volumes:
      - ./src/:/var/www/html/
  mysql:
    build: './docker/mysql/'
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: svitts
      MYSQL_USER: foo
      MYSQL_PASSWORD: bar
networks:
  frontend:
  backend: